### ISSUE TITLE
Computed properties, property observers

### ISSUE THREAD

**Issue by klebba** [kenchris/lit-element#15]
Polymer's `properties` block allows me to decorate each property with `computed` and `observer` definitions which I can use to create property pipelines and side effects when properties change. Will you consider this kind of feature in the roadmap for `lit-element`?

Thanks!

**Comment by kenchris** [comment]
I am definitely open to adding more features if there is a value.

But we need to make sure the convenience outweighs the size gains and we need to make sure they can be implemented efficiency and in a way that people will use them efficiency.

Talking to Justin from the Polymer team, I got a sense that there was a few things that maybe wasn't that best idea in Polymer, like for instance the auto conversion of cases (attributes - property mapping) which is why I added attrName instead. Also, after talking to him I added the renderCallback() / render() pair.

That should allow you to easily do preprocessing of properties before paint. Just reimplement renderCallback() so add pre and post processing code and call then super.render() inside.

I added a bit of documentation about this in the README.md

If you have use-cases that are not solved this this, or so common that we need something else, please share these :-)

**Comment by klebba** [comment]
Cool, this is a helpful example. One use case not solved by `renderCallback` is a computed+reflected property -- the attribute reflection logic will have to be manually implemented in `renderCallback` which duplicates the logic in the getter/setter prop configuration

**Comment by kenchris** [comment]
Could you give an example of what you mean and why it is useful?

**Comment by klebba** [comment]
@kenchris I missed your response. I'm hoping for functionality similar to what's available in Polymer: https://www.polymer-project.org/2.0/docs/devguide/observers#computed-properties

**Comment by kenchris** [comment]
That would be useful, that way I can see if this is the best way of accomplishing that.

**Comment by kenchris** [comment]
OK, implemented "computed"
