### ISSUE TITLE
Example event handler / listener

### ISSUE THREAD

**Issue by bradrydzewski** [kenchris/lit-element#29]
Hi there, I was wondering if you could post an example in the README or in this issue for handling events. For discussion purposes, lets say we have the following component:

```
class Prompt extends LitElement {
  render() {
    return html`
      <div>
        <button>Continue</button>
        <button>Cancel</button>
      </div>
    `
}

customElements.define('prompt-element', Prompt.withProperties());
```

How would one go about doing something like this:

```
<prompt-element on-continue=... on-cancel=...></prompt-element>
```

I tried passing functions as properties but couldn't get it working. I also noticed a recently added `listener` capability which seemed promising. I would really appreciate any tips you can provide :)

**Comment by filipbech** [comment]
The general idea would be to use native dom-events. 
Since htmlElement extends eventTarget you can do this.dispatchEvent(new CustomEvent(“event-name”, {detail: “data”})); from within... then regular event listening would capture the event. So on-event-name (if you use litExtended) or just addEventListener would work. 
Does this answer your question? You can also use functions as properties and call from your function but events are very appropriate for this and they buble up the tree, so you can catch them from any ancestor.

**Comment by filipbech** [comment]
You can see how it could look in this “old” example I made. 

https://github.com/filipbech/lit-element-example/blob/master/demo.js

**Comment by bradrydzewski** [comment]
Ahhh .... I was close but was mistakenly including the `on-` prefix in the event name. Your example helped me resolve the issue and everything works perfectly now. Thanks so much for taking the time to help, even though it was a clear case of user error :)

```diff
-this.dispatchEvent(new CustomEvent('on-continue'));
+this.dispatchEvent(new CustomEvent('continue'));
```
